詳細ページを実装しました。
tomoki23/laravel_task_image_app pull request #4
Opened 2023-06-04 05:33 UTC by tomoki23

### show.blade.php
・詳細画面を作成
・更新ボタンと削除ボタンはログイン中のユーザーidとタスクに登録されているユーザーidが一致した時だけ表示
・コメント機能はまだ実装していません。

### web.php
・showのルートを追加
・不要なコードを削除

### TaskController (show)
・単一のモデルを取得
・取得したタスクのステータスを定義

を実装しました。
確認お願いいたします。

2023-06-04 09:07 UTC, MizukiMatsutani requested changes
@tomoki23 
確認下さい！

2023-06-04 09:07 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +        $task = Task::find($id);
データがない場合に備えてfindOrFailを使うと良いです！

2023-06-04 09:07 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +        $task = Task::find($id);
あとwithでeager loadしとかないとです！

2023-06-04 09:07 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +        $status = $statusLabels[$task->status];
こちらモデルのアクセサという機能でカプセル化すると便利ですよ！

2023-06-06 13:33 UTC, tomoki23 commented
### TaskModel
・statusのアクセサを定義
・assignedUserメソッドの定義
・$fillableにassigned_user_idを追加

### TaskController
・storeメソッドのユーザーidを修正
・storeメソッドにassignedUserIdを追加
・showメソッドの$taskにwithを追加とfindをfindOrFailに変更

### TaskFactory
・assigned_user_idを追加

### create_tasks_table.php
・assigned_user_idを追加

### create.blade.php
・ユーザーを担当ユーザーに変更

### show.blade.php
・更新ボタンと削除ボタンの表示条件を変更
・担当者名を表示

を実装しました。
確認よろしくお願いします。

2023-06-09 12:29 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +        return view('tasks.show', compact('task', 'status'));
@tomoki23 
こちら、$taskを渡せば、blade側で$task->statusすればいいので、わざわざコントローラーで$statusに切り出さなくていいとおもいます！！

2023-06-10 05:26 UTC, tomoki23 commented
### TaskController
・$statusを削除

### show.blade.php
・$statusを$task->status

修正しました。
確認お願いいたします。

2023-06-14 00:17 UTC, merged