コメント表示機能を実装しました。
tomoki23/laravel_task_image_app pull request #8
Opened 2023-06-19 12:02 UTC by tomoki23

### TaskController (show)
・showメソッドにコメントのデータを追加

### CommentFactory
・コメント用のダミーデータ作成

### CommentSeeder
・CommentFactoryの呼び出し

### DatabaseSeeder
・CommentSeederの呼び出し

### show.blade.php
・コメント表示部分を追加

### Comment.php
・CommentModel作成
・ユーザーとタスクのリレーション設定

実装しました。
確認お願いいたします。

2023-06-20 00:19 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +        $comments = Comment::with(['user', 'task'])->get();
リレーションの機能を使えば、$taskからcommentsは取得できます！
わざわざCommentテーブルから取得することはしなくて良いですよ！
（しかもこれだと全コメント取得してませんか？対象タスクのコメントだけでいいはずです）

2023-06-20 00:20 UTC, MizukiMatsutani commented on resources/views/tasks/show.blade.php
> +          @foreach ($comments as $comment)
コメント全件取得してるからココでループしてタスクIDの一致の条件が発生しています。
$taskに紐づくCommentをリレーションで取得するなら不要になります（Commentの有無をチェックする必要はありますが）

2023-06-20 00:21 UTC, MizukiMatsutani requested changes
@tomoki23 
コメントしました！

2023-06-24 12:56 UTC, tomoki23 commented
###  TaskController (show)
・コメントをタスクから取得するように修正

### show.blade.php
・コメント部分修正

### Task.php
・commentのリレーション設定

修正しました。
確認お願いいたします。

2023-06-25 01:56 UTC, MizukiMatsutani requested changes

2023-06-25 01:56 UTC, MizukiMatsutani commented on resources/views/tasks/show.blade.php
> +                  @if ($task->comments)
このifは不要です！
foreachは空であればループしないので！

2023-06-25 06:30 UTC, tomoki23 commented
### show.blade.php
・コメント部分のif文を削除

確認お願いいたします。

2023-06-26 00:25 UTC, merged